// AUTO-GENERATED by scripts/generateMemeTextZones.mjs — DO NOT EDIT BY HAND.
// Source: PanelHaus (Comic-Pro2) memeTemplates.js + memeFontPresets.js, converted
// to normalized 0–1 zones via the real resolveMemeBubbleStyle. Re-run the script
// to regenerate, or edit via the in-app admin calibrator (Copy JSON → paste here).
import type { MemeZoneRegistry } from "../from-meme/zoneTypes";

export const MEME_TEXT_ZONES: MemeZoneRegistry = {
  "drake-hotline-bling": {
    "aspect": 1,
    "image": "drake-hotline-bling.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.537,
        "y": 0.089,
        "width": 0.4329,
        "height": 0.28,
        "fontSizeRatio": 0.0766,
        "text": "floor price",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.519,
        "y": 0.596,
        "width": 0.4543,
        "height": 0.2329,
        "fontSizeRatio": 0.0758,
        "text": "utility",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "distracted-boyfriend": {
    "aspect": 1.4989,
    "image": "distracted-boyfriend.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.187,
        "y": 0.014,
        "width": 0.6071,
        "height": 0.2099,
        "fontSizeRatio": 0.05,
        "text": "you eyeing the next mint",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "batman-slapping-robin": {
    "aspect": 1.034,
    "image": "batman-slapping-robin.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.045,
        "y": 0.015,
        "width": 0.41,
        "height": 0.1758,
        "fontSizeRatio": 0.067,
        "text": "My parents are ali..",
        "style": {
          "color": "#000000",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.577,
        "y": 0.022,
        "width": 0.377,
        "height": 0.175,
        "fontSizeRatio": 0.0678,
        "text": "UNDEAD",
        "style": {
          "color": "#000000",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "change-my-mind": {
    "aspect": 1.3359,
    "image": "change-my-mind.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.408,
        "y": 0.622,
        "width": 0.478,
        "height": 0.219,
        "rotation": -6,
        "fontSizeRatio": 0.0429,
        "text": "Betty is the blueprint",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "two-buttons": {
    "aspect": 0.66,
    "image": "two-buttons.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.07,
        "y": 0.093,
        "width": 0.4329,
        "height": 0.0943,
        "rotation": -14.8,
        "fontSizeRatio": 0.0581,
        "text": "hold",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.366,
        "y": 0.055,
        "width": 0.4329,
        "height": 0.0943,
        "rotation": -14.8,
        "fontSizeRatio": 0.0498,
        "text": "panic sell",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "left-exit-12": {
    "aspect": 1.0479,
    "image": "left-exit-12.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.2957,
        "y": 0.25,
        "width": 0.2271,
        "height": 0.1722,
        "fontSizeRatio": 0.0457,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.6186,
        "y": 0.2395,
        "width": 0.3,
        "height": 0.1572,
        "fontSizeRatio": 0.0486,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-3",
        "x": 0.5029,
        "y": 0.6991,
        "width": 0.41,
        "height": 0.1946,
        "fontSizeRatio": 0.06,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "anakin-padme": {
    "aspect": 1,
    "image": "anakin-padme.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.045,
        "y": 0.312,
        "width": 0.4714,
        "height": 0.1714,
        "fontSizeRatio": 0.06,
        "text": "for the floor",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.543,
        "y": 0.33,
        "width": 0.4571,
        "height": 0.1714,
        "fontSizeRatio": 0.06,
        "text": ". . . right?",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-3",
        "x": 0.529,
        "y": 0.771,
        "width": 0.4571,
        "height": 0.2271,
        "fontSizeRatio": 0.1343,
        "text": "...",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "one-does-not-simply": {
    "aspect": 1.6949,
    "image": "one-does-not-simply.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.118,
        "y": 0.035,
        "width": 0.7143,
        "height": 0.1937,
        "fontSizeRatio": 0.06,
        "text": "one does not simply",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.168,
        "y": 0.777,
        "width": 0.7143,
        "height": 0.1937,
        "fontSizeRatio": 0.06,
        "text": "exit the deadzone",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "this-is-fine": {
    "aspect": 2.0588,
    "image": "this-is-fine.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0,
        "y": 0.012,
        "width": 0.5329,
        "height": 0.3647,
        "fontSizeRatio": 0.06,
        "text": "the floor is on fire. gm",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "anime-girl-hiding-from-terminator": {
    "aspect": 0.9186,
    "image": "anime-girl-hiding-from-terminator.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.029,
        "y": 0.017,
        "width": 0.357,
        "height": 0.1,
        "fontSizeRatio": 0.07,
        "text": "Rugger",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.296,
        "y": 0.777,
        "width": 0.6485,
        "height": 0.1,
        "fontSizeRatio": 0.07,
        "text": "hiding from the rug",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "bernie-sanders-once-again-asking": {
    "aspect": 1.3462,
    "image": "bernie-sanders-once-again-asking.webp",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.088,
        "y": 0.023,
        "width": 0.8329,
        "height": 0.1923,
        "fontSizeRatio": 0.0643,
        "text": "I am once again asking for",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.089,
        "y": 0.734,
        "width": 0.8329,
        "height": 0.1923,
        "fontSizeRatio": 0.0643,
        "text": "For the floor",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "bike-fall": {
    "aspect": 0.7357,
    "image": "bike-fall.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.523,
        "y": 0.101,
        "width": 0.4408,
        "height": 0.1371,
        "fontSizeRatio": 0.0641,
        "text": "bags finally recovering",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.016,
        "y": 0.465,
        "width": 0.4408,
        "height": 0.1914,
        "fontSizeRatio": 0.0641,
        "text": "me revenge trading at 3am",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-3",
        "x": 0.531,
        "y": 0.696,
        "width": 0.4408,
        "height": 0.1371,
        "fontSizeRatio": 0.0641,
        "text": "who keeps rugging me",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "futurama-fry": {
    "aspect": 1.3333,
    "image": "futurama-fry.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.143,
        "y": 0.096,
        "width": 0.648,
        "height": 0.108,
        "fontSizeRatio": 0.0643,
        "text": "not sure if dip",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.243,
        "y": 0.773,
        "width": 0.476,
        "height": 0.134,
        "fontSizeRatio": 0.0643,
        "text": "or rug",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "grandma-finds-the-internet": {
    "aspect": 1.3333,
    "image": "grandma-finds-the-internet.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.047,
        "y": 0.03,
        "width": 0.9214,
        "height": 0.1524,
        "fontSizeRatio": 0.0786,
        "text": "just discovered the horde",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "grus-plan": {
    "aspect": 1.559,
    "image": "grus-plan.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.294,
        "y": 0.208,
        "width": 0.1857,
        "height": 0.1782,
        "fontSizeRatio": 0.0456,
        "text": "step 1: buy",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.789,
        "y": 0.23,
        "width": 0.1857,
        "height": 0.1782,
        "fontSizeRatio": 0.0456,
        "text": "step 2: hold",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-3",
        "x": 0.293,
        "y": 0.718,
        "width": 0.1857,
        "height": 0.1782,
        "fontSizeRatio": 0.0456,
        "text": "step 3: hold",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-4",
        "x": 0.788,
        "y": 0.687,
        "width": 0.1857,
        "height": 0.265,
        "fontSizeRatio": 0.0456,
        "text": "step 4: still holding",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "hide-the-pain-harold": {
    "aspect": 0.7986,
    "image": "hide-the-pain-harold.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.042,
        "y": 0.018,
        "width": 0.8945,
        "height": 0.1143,
        "fontSizeRatio": 0.0751,
        "text": "holding strong",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.043,
        "y": 0.516,
        "width": 0.8945,
        "height": 0.1143,
        "fontSizeRatio": 0.0751,
        "text": "in agony",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "monkey-puppet": {
    "aspect": 1.2007,
    "image": "monkey-puppet.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.2329,
        "y": 0.1887,
        "width": 0.9143,
        "height": 0.1201,
        "fontSizeRatio": 0.06,
        "text": "Your text here",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.7171,
        "y": 0.1921,
        "width": 0.87,
        "height": 0.1201,
        "fontSizeRatio": 0.06,
        "text": "Your text here",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "mother-ignoring-kid-drowning": {
    "aspect": 0.7571,
    "image": "mother-ignoring-kid-drowning.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.583,
        "y": 0.1129,
        "width": 0.566,
        "height": 0.1,
        "fontSizeRatio": 0.0792,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.2774,
        "y": 0.5529,
        "width": 0.566,
        "height": 0.1,
        "fontSizeRatio": 0.0792,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-3",
        "x": 0.5019,
        "y": 0.8914,
        "width": 0.566,
        "height": 0.1,
        "fontSizeRatio": 0.0792,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "roll-safe": {
    "aspect": 1.7766,
    "image": "roll-safe.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.046,
        "y": 0.033,
        "width": 0.9143,
        "height": 0.1777,
        "fontSizeRatio": 0.06,
        "text": "can't get rugged if you never sell",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "spider-man-triple": {
    "aspect": 1.0886,
    "image": "spider-man-triple.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.182,
        "y": 0.037,
        "width": 0.637,
        "height": 0.111,
        "fontSizeRatio": 0.0581,
        "text": "which of us aped first?",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "surprised-pikachu": {
    "aspect": 1,
    "image": "surprised-pikachu.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.038,
        "y": 0.116,
        "width": 0.9143,
        "height": 0.1143,
        "fontSizeRatio": 0.0807,
        "text": "sold the floor, it pumped",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "three-headed-dragon": {
    "aspect": 1.25,
    "image": "three-headed-dragon.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.8057,
        "y": 0.3125,
        "width": 0.4543,
        "height": 0.1893,
        "fontSizeRatio": 0.0557,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.4957,
        "y": 0.1714,
        "width": 0.4543,
        "height": 0.1893,
        "fontSizeRatio": 0.0557,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-3",
        "x": 0.1843,
        "y": 0.2964,
        "width": 0.4543,
        "height": 0.1893,
        "fontSizeRatio": 0.0557,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "trump-bill-signing": {
    "aspect": 1.2195,
    "image": "trump-bill-signing.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.39,
        "y": 0.446,
        "width": 0.2643,
        "height": 0.176,
        "fontSizeRatio": 0.0452,
        "text": "hereby declares:",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.695,
        "y": 0.446,
        "width": 0.2371,
        "height": 0.1829,
        "fontSizeRatio": 0.0452,
        "text": "stay dead",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "tuxedo-winnie-the-pooh": {
    "aspect": 1.3752,
    "image": "tuxedo-winnie-the-pooh.webp",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.479,
        "y": 0.088,
        "width": 0.5114,
        "height": 0.2947,
        "fontSizeRatio": 0.0635,
        "text": "holding ",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.467,
        "y": 0.544,
        "width": 0.516,
        "height": 0.342,
        "fontSizeRatio": 0.0638,
        "text": "but make it classy",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "who-killed-hannibal": {
    "aspect": 0.8886,
    "image": "who-killed-hannibal.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.013,
        "y": 0.862,
        "width": 0.9871,
        "height": 0.1,
        "fontSizeRatio": 0.0675,
        "text": "why would the horde do this?",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "x-everywhere": {
    "aspect": 1.4706,
    "image": "x-everywhere.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.086,
        "y": 0.041,
        "width": 0.787,
        "height": 0.157,
        "fontSizeRatio": 0.0714,
        "text": "fellaz",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.13,
        "y": 0.776,
        "width": 0.774,
        "height": 0.134,
        "fontSizeRatio": 0.0714,
        "text": "fellaz everywhere",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "you-guys-are-getting-paid": {
    "aspect": 1.4523,
    "image": "you-guys-are-getting-paid.webp",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.4471,
        "y": 0.1079,
        "width": 0.9143,
        "height": 0.166,
        "fontSizeRatio": 0.0657,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.4714,
        "y": 0.8672,
        "width": 0.9143,
        "height": 0.166,
        "fontSizeRatio": 0.0657,
        "text": "You guys are getting paid?",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "is-this-a-butterfly": {
    "aspect": 1.1129,
    "image": "is-this-a-butterfly.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.159,
        "y": 0.806,
        "width": 0.6814,
        "height": 0.1208,
        "fontSizeRatio": 0.06,
        "text": "is this the flippening?",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "patrick-to-do-list": {
    "aspect": 1.5982,
    "image": "patrick-to-do-list.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.341,
        "y": 0.284,
        "width": 0.33,
        "height": 0.484,
        "rotation": -15,
        "fontSizeRatio": 0.0529,
        "text": "step 1: stay dead",
        "style": {
          "color": "#000000",
          "fontFamily": "Arial, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "two-paths": {
    "aspect": 1,
    "image": "two-paths.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.607,
        "y": 0.262,
        "width": 0.3429,
        "height": 0.1643,
        "fontSizeRatio": 0.0766,
        "text": "or ape?",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.053,
        "y": 0.245,
        "width": 0.3429,
        "height": 0.17,
        "fontSizeRatio": 0.0678,
        "text": "Hold",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "absolute-cinema": {
    "aspect": 1.2915,
    "image": "absolute-cinema.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.112,
        "y": 0.776,
        "width": 0.8143,
        "height": 0.1236,
        "fontSizeRatio": 0.0678,
        "text": "the horde in 4k",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "astronaut-always-has-been": {
    "aspect": 1.7766,
    "image": "astronaut-always-has-been.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.215,
        "y": 0.067,
        "width": 0.5771,
        "height": 0.1497,
        "fontSizeRatio": 0.06,
        "text": "wait, it's all betty",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.178,
        "y": 0.756,
        "width": 0.7486,
        "height": 0.1777,
        "fontSizeRatio": 0.06,
        "text": "always has been",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "bad-luck-brian": {
    "aspect": 0.8443,
    "image": "bad-luck-brian.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.152,
        "y": 0.044,
        "width": 0.7817,
        "height": 0.0986,
        "fontSizeRatio": 0.0778,
        "text": "bought the top",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.105,
        "y": 0.853,
        "width": 0.8003,
        "height": 0.0957,
        "fontSizeRatio": 0.0778,
        "text": "sold the bottom",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "buff-doge-cheems": {
    "aspect": 1.2132,
    "image": "buff-doge-cheems.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.069,
        "y": 0.051,
        "width": 0.4129,
        "height": 0.2062,
        "fontSizeRatio": 0.0766,
        "text": "me 2021",
        "style": {
          "color": "#000000",
          "fontFamily": "\"Inter\", Arial, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.577,
        "y": 0.195,
        "width": 0.4229,
        "height": 0.2201,
        "fontSizeRatio": 0.0762,
        "text": "me now",
        "style": {
          "color": "#000000",
          "fontFamily": "\"Inter\", Arial, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "charlie-conspiracy": {
    "aspect": 1.3333,
    "image": "charlie-conspiracy.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.091,
        "y": 0.045,
        "width": 0.8,
        "height": 0.12,
        "fontSizeRatio": 0.06,
        "text": "it's all connected to the rug",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "dafoe-looking-up": {
    "aspect": 1.7766,
    "image": "dafoe-looking-up.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.109,
        "y": 0.035,
        "width": 0.7714,
        "height": 0.1751,
        "fontSizeRatio": 0.06,
        "text": "staring up the green candle",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "empty-stonks": {
    "aspect": 1.3333,
    "image": "empty-stonks.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.018,
        "y": 0.02,
        "width": 0.691,
        "height": 0.125,
        "fontSizeRatio": 0.0639,
        "text": "number go down",
        "style": {
          "color": "#000000",
          "fontFamily": "\"Inter\", Arial, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.496,
        "y": 0.583,
        "width": 0.484,
        "height": 0.121,
        "fontSizeRatio": 0.0528,
        "text": "up only i swear",
        "style": {
          "color": "#000000",
          "fontFamily": "\"Inter\", Arial, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "family-guy-lois-pills": {
    "aspect": 1.072,
    "image": "family-guy-lois-pills.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.047,
        "y": 0.463,
        "width": 0.2729,
        "height": 0.1914,
        "fontSizeRatio": 0.06,
        "text": "green pills",
        "style": {
          "color": "#000000",
          "fontFamily": "\"Inter\", Arial, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.549,
        "y": 0.069,
        "width": 0.4457,
        "height": 0.2098,
        "fontSizeRatio": 0.06,
        "text": "just take the green pills",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "first-time": {
    "aspect": 0.9257,
    "image": "first-time.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.4846,
        "y": 0.0414,
        "width": 0.8009,
        "height": 0.1014,
        "fontSizeRatio": 0.0648,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.4599,
        "y": 0.5643,
        "width": 0.8009,
        "height": 0.1,
        "fontSizeRatio": 0.0648,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "hand-on-shoulder": {
    "aspect": 1.354,
    "image": "hand-on-shoulder.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.053,
        "y": 0.794,
        "width": 0.9186,
        "height": 0.118,
        "fontSizeRatio": 0.06,
        "text": "it's okay fella, we all aped the top",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "holding-fart": {
    "aspect": 0.7457,
    "image": "holding-fart.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.199,
        "y": 0.133,
        "width": 0.8008,
        "height": 0.1,
        "fontSizeRatio": 0.0805,
        "text": "holding the bag",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.094,
        "y": 0.83,
        "width": 0.8008,
        "height": 0.0929,
        "fontSizeRatio": 0.0805,
        "text": "with a straight face",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "most-interesting-man": {
    "aspect": 0.7971,
    "image": "most-interesting-man.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0,
        "y": 0.043,
        "width": 0.953,
        "height": 0.151,
        "fontSizeRatio": 0.081,
        "text": "i don't always sell",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.045,
        "y": 0.806,
        "width": 0.855,
        "height": 0.118,
        "fontSizeRatio": 0.0729,
        "text": "but when i do i hold",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "office-congratulations": {
    "aspect": 1.0495,
    "image": "office-congratulations.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.053,
        "y": 0.263,
        "width": 0.4629,
        "height": 0.1244,
        "fontSizeRatio": 0.06,
        "text": "congratulation",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.439,
        "y": 0.629,
        "width": 0.5614,
        "height": 0.1034,
        "fontSizeRatio": 0.06,
        "text": "you survived the dip",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "sad-happy-bus": {
    "aspect": 1.1272,
    "image": "sad-happy-bus.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.023,
        "y": 0.384,
        "width": 0.432,
        "height": 0.133,
        "fontSizeRatio": 0.06,
        "text": "paper hands",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.477,
        "y": 0.375,
        "width": 0.5229,
        "height": 0.0982,
        "fontSizeRatio": 0.06,
        "text": "the horde",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "shut-up-take-my-money": {
    "aspect": 1.7766,
    "image": "shut-up-take-my-money.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.047,
        "y": 0.022,
        "width": 0.8286,
        "height": 0.1802,
        "fontSizeRatio": 0.06,
        "text": "shut up and take my eth",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "sure-grandma": {
    "aspect": 1.12,
    "image": "sure-grandma.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.015,
        "y": 0.671,
        "width": 0.7514,
        "height": 0.1296,
        "fontSizeRatio": 0.06,
        "text": "nfts are dead",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.454,
        "y": 0.325,
        "width": 0.5457,
        "height": 0.2672,
        "fontSizeRatio": 0.0514,
        "text": "sure grandma , off to discord we go",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "talking-to-wall": {
    "aspect": 1.7766,
    "image": "talking-to-wall.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.3514,
        "y": 0.2234,
        "width": 0.6843,
        "height": 0.1904,
        "fontSizeRatio": 0.06,
        "text": "Your text here",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "thinking-about-girls": {
    "aspect": 1.7766,
    "image": "thinking-about-girls.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.22,
        "y": 0.5279,
        "width": 0.4486,
        "height": 0.1827,
        "fontSizeRatio": 0.06,
        "text": "Your text here",
        "style": {
          "color": "#000000",
          "fontFamily": "\"Inter\", Arial, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.6957,
        "y": 0.7335,
        "width": 0.6843,
        "height": 0.203,
        "fontSizeRatio": 0.06,
        "text": "Your text here",
        "style": {
          "color": "#000000",
          "fontFamily": "\"Inter\", Arial, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "running-away-balloon": {
    "aspect": 0.7429,
    "image": "running-away-balloon.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.035,
        "y": 0.015,
        "width": 0.3404,
        "height": 0.16,
        "fontSizeRatio": 0.0808,
        "text": "you",
        "style": {
          "color": "#0a0a0b",
          "fontFamily": "Arial, Helvetica, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.546,
        "y": 0.125,
        "width": 0.4538,
        "height": 0.1543,
        "fontSizeRatio": 0.0615,
        "text": "reaching for the pump",
        "style": {
          "color": "#0a0a0b",
          "fontFamily": "Arial, Helvetica, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      },
      {
        "id": "zone-3",
        "x": 0.018,
        "y": 0.748,
        "width": 0.3962,
        "height": 0.2014,
        "fontSizeRatio": 0.0615,
        "text": "held back by paperhands",
        "style": {
          "color": "#0a0a0b",
          "fontFamily": "Arial, Helvetica, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "squid-game": {
    "aspect": 0.6485,
    "image": "squid-game.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.054,
        "y": 0.027,
        "width": 0.896,
        "height": 0.1349,
        "fontSizeRatio": 0.07,
        "text": "fella's pumping,\nwe're so back",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      },
      {
        "id": "zone-2",
        "x": 0.073,
        "y": 0.504,
        "width": 0.866,
        "height": 0.0908,
        "fontSizeRatio": 0.07,
        "text": "dead cat bounce",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "obama-medal": {
    "aspect": 1.618,
    "image": "obama-medal.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.093,
        "y": 0.021,
        "width": 0.8393,
        "height": 0.152,
        "fontSizeRatio": 0.0519,
        "text": "promoting myself to horde general",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "wolverine-remember": {
    "aspect": 0.6844,
    "image": "wolverine-remember.png",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.316,
        "y": 0.566,
        "width": 0.3375,
        "height": 0.2425,
        "fontSizeRatio": 0.0587,
        "text": "remember when the floor was alive",
        "style": {
          "color": "#0a0a0b",
          "fontFamily": "Arial, Helvetica, sans-serif",
          "fontWeight": 400,
          "italic": false,
          "allCaps": false,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": null,
          "box": null
        }
      }
    ]
  },
  "spongebob-rainbow": {
    "aspect": 1.3333,
    "image": "spongebob-rainbow.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.161,
        "y": 0.083,
        "width": 0.6694,
        "height": 0.2,
        "fontSizeRatio": 0.0677,
        "text": "utility",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "crossed-eye-spongebob": {
    "aspect": 1.2584,
    "image": "crossed-eye-spongebob.webp",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.061,
        "y": 0,
        "width": 0.9,
        "height": 0.1594,
        "fontSizeRatio": 0.0633,
        "text": "doing my own research",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "black-guy-hiding-behind-tree": {
    "aspect": 0.8019,
    "image": "black-guy-hiding-behind-tree.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.068,
        "y": 0.784,
        "width": 0.8515,
        "height": 0.171,
        "fontSizeRatio": 0.0698,
        "text": "lurking till my bag recovers",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "peace-sign-tombstone": {
    "aspect": 1.1752,
    "image": "peace-sign-tombstone.jpg",
    "zones": [
      {
        "id": "zone-1",
        "x": 0.11,
        "y": 0.257,
        "width": 0.283,
        "height": 0.231,
        "fontSizeRatio": 0.044,
        "text": "rip to everyone who sold the bottom",
        "style": {
          "color": "#ffffff",
          "fontFamily": "Anton, 'Arial Black', Impact, sans-serif",
          "fontWeight": 700,
          "italic": false,
          "allCaps": true,
          "textAlign": "center",
          "lineHeight": 1.1,
          "outline": {
            "color": "#000000",
            "widthEm": 0.09
          },
          "box": null
        }
      }
    ]
  },
  "spongebob-burning-paper": {
    "aspect": 0.826,
    "image": "spongebob-burning-paper.jpg",
    "zones": []
  },
  "first-world-problems": {
    "aspect": 1.5041,
    "image": "first-world-problems.jpg",
    "zones": []
  },
  "im-the-captain-now": {
    "aspect": 1.3657,
    "image": "im-the-captain-now.jpg",
    "zones": []
  },
  "uno-draw-25-cards": {
    "aspect": 1.0121,
    "image": "uno-draw-25-cards.jpg",
    "zones": []
  }
};
